# Generated by Django 2.2.12 on 2022-03-23 09:02

from django.db import migrations, models
import django.db.models.deletion
import otree.db.idmap
import otree.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('otree', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_in_subsession', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dual_group', to='otree.Session')),
            ],
            options={
                'db_table': 'DUAL_group',
            },
            bases=(models.Model, otree.db.idmap.GroupIDMapMixin),
        ),
        migrations.CreateModel(
            name='Subsession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dual_subsession', to='otree.Session')),
            ],
            options={
                'db_table': 'DUAL_subsession',
            },
            bases=(models.Model, otree.db.idmap.SubsessionIDMapMixin),
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_in_group', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('_payoff', otree.db.models.CurrencyField(default=0, null=True)),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('_role', otree.db.models.StringField(max_length=10000, null=True)),
                ('right_side_amount', otree.db.models.CurrencyField(default=15, null=True)),
                ('switching_point', otree.db.models.CurrencyField(null=True)),
                ('comm_1', otree.db.models.StringField(blank=True, max_length=10000, null=True, verbose_name='Platz für Kommentare, falls Ihnen die Beschreibungen auf dieser Seite unklar erscheinen')),
                ('comm_2', otree.db.models.StringField(blank=True, max_length=10000, null=True, verbose_name='Platz für Kommentare, falls Ihnen die Beschreibungen auf dieser Seite unklar erscheinen')),
                ('comm_3', otree.db.models.StringField(blank=True, max_length=10000, null=True, verbose_name='Platz für Kommentare, falls Ihnen die Fragen auf dieser Seite unklar erscheinen')),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='DUAL.Group')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dual_player', to='otree.Participant')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dual_player', to='otree.Session')),
                ('subsession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DUAL.Subsession')),
            ],
            options={
                'db_table': 'DUAL_player',
            },
            bases=(models.Model, otree.db.idmap.PlayerIDMapMixin),
        ),
        migrations.AddField(
            model_name='group',
            name='subsession',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DUAL.Subsession'),
        ),
    ]
