# Generated by Django 2.2.12 on 2022-03-23 09:02

from django.db import migrations, models
import django.db.models.deletion
import otree.db.idmap
import otree.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('otree', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_in_subsession', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wasser_aufbereitung_group', to='otree.Session')),
            ],
            options={
                'db_table': 'wasser_aufbereitung_group',
            },
            bases=(models.Model, otree.db.idmap.GroupIDMapMixin),
        ),
        migrations.CreateModel(
            name='Subsession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wasser_aufbereitung_subsession', to='otree.Session')),
            ],
            options={
                'db_table': 'wasser_aufbereitung_subsession',
            },
            bases=(models.Model, otree.db.idmap.SubsessionIDMapMixin),
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_in_group', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('_payoff', otree.db.models.CurrencyField(default=0, null=True)),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('_role', otree.db.models.StringField(max_length=10000, null=True)),
                ('wasser_aufbereitung', otree.db.models.IntegerField(choices=[[0, 'Strom'], [1, 'Gas'], [2, 'Öl'], [3, 'Auf andere Weise'], [4, 'Ich weiß es nicht./ Keine Angabe']], null=True, verbose_name='')),
                ('wasser_aufbereitung_kommentare', otree.db.models.StringField(blank=True, max_length=10000, null=True, verbose_name='')),
                ('durchlauferhiter', otree.db.models.IntegerField(choices=[[0, 'Ja'], [1, 'Nein'], [2, 'Ich weiß es nicht./ Keine Angabe']], null=True, verbose_name='Befindet sich in Ihrem Badezimmer ein Durchlauferhitzer?')),
                ('strom', otree.db.models.IntegerField(choices=[[0, 'Ja, Ökostromanbieter'], [1, 'Ja, Ökostromtarif eines konventionellen Anbieters'], [2, 'Nein, keines von Beiden'], [3, 'Ich weiß es nicht./ Keine Angabe']], null=True, verbose_name='Beziehen Sie Ihren Strom von einem Ökostromanbieter oder haben Sie einen Ökostromtarif eines konventionellen Stromanbieters gewählt?')),
                ('gas', otree.db.models.IntegerField(choices=[[0, 'Ich beziehe kein Gas'], [1, 'Ja, Ökogasanbieter'], [2, 'Ja, Ökogastarif'], [3, 'Nein, keines von Beiden'], [4, 'Ich weiß es nicht./ Keine Angabe']], null=True, verbose_name='Beziehen Sie Ihr Gas von einem Ökogasanbieter oder haben Sie einen Ökogastarif eines konventionellen Gasanbieters gewählt?')),
                ('solar', otree.db.models.IntegerField(choices=[[0, 'Ja'], [1, 'Nein'], [3, 'Ich weiß es nicht./ Keine Angabe']], null=True, verbose_name='Befindet sich auf dem Dach Ihres Hauses eine Photovoltaikanlage/Solaranlage/Solarthermieanlage? ')),
                ('comm_1', otree.db.models.StringField(blank=True, max_length=10000, null=True, verbose_name='Platz für Kommentare, falls die auf dieser Seite gestellten Fragen unverständlich sind')),
                ('comm_2', otree.db.models.StringField(blank=True, max_length=10000, null=True, verbose_name='Platz für Kommentare, falls die auf dieser Seite gestellten Fragen unverständlich sind')),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wasser_aufbereitung.Group')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wasser_aufbereitung_player', to='otree.Participant')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wasser_aufbereitung_player', to='otree.Session')),
                ('subsession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wasser_aufbereitung.Subsession')),
            ],
            options={
                'db_table': 'wasser_aufbereitung_player',
            },
            bases=(models.Model, otree.db.idmap.PlayerIDMapMixin),
        ),
        migrations.AddField(
            model_name='group',
            name='subsession',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wasser_aufbereitung.Subsession'),
        ),
    ]
