# Generated by Django 2.2.12 on 2022-03-23 09:02

from django.db import migrations, models
import django.db.models.deletion
import otree.db.idmap
import otree.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('otree', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_in_subsession', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='umwelt_einstellung_group', to='otree.Session')),
            ],
            options={
                'db_table': 'umwelt_einstellung_group',
            },
            bases=(models.Model, otree.db.idmap.GroupIDMapMixin),
        ),
        migrations.CreateModel(
            name='Subsession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='umwelt_einstellung_subsession', to='otree.Session')),
            ],
            options={
                'db_table': 'umwelt_einstellung_subsession',
            },
            bases=(models.Model, otree.db.idmap.SubsessionIDMapMixin),
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_in_group', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('_payoff', otree.db.models.CurrencyField(default=0, null=True)),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('_role', otree.db.models.StringField(max_length=10000, null=True)),
                ('e_11', otree.db.models.TableField(choices=[[0, ''], [1, ''], [2, ''], [3, ''], [4, ''], [5, ''], [6, ''], [7, ''], [8, ''], [9, '']], null=True, verbose_name='Ich bin bereit, mich umweltschonend zu verhalten, auch wenn dies mit höheren Kosten und Anstrengungen verbunden ist.')),
                ('e_12', otree.db.models.TableField(choices=[[0, ''], [1, ''], [2, ''], [3, ''], [4, ''], [5, ''], [6, ''], [7, ''], [8, ''], [9, '']], null=True, verbose_name='Ich bin nur dann bereit, mich umweltschonend zu verhalten, wenn andere das auch tun.')),
                ('e_13', otree.db.models.TableField(choices=[[0, ''], [1, ''], [2, ''], [3, ''], [4, ''], [5, ''], [6, ''], [7, ''], [8, ''], [9, '']], null=True, verbose_name='Es entspricht meinen Prinzipien, Ressourcen (z.B. Energie, Wasser) zu sparen.')),
                ('e_14', otree.db.models.TableField(choices=[[0, ''], [1, ''], [2, ''], [3, ''], [4, ''], [5, ''], [6, ''], [7, ''], [8, ''], [9, '']], null=True, verbose_name='Ich fühle mich persönlich dafür verantwortlich, Ressourcen zu sparen.')),
                ('e_21', otree.db.models.TableField(choices=[[0, ''], [1, ''], [2, ''], [3, ''], [4, ''], [5, ''], [6, ''], [7, ''], [8, ''], [9, '']], null=True, verbose_name='Die meisten Menschen, die mir wichtig sind, finden, ich sollte versuchen, möglichst wenig Ressourcen (z.B. Energie, Wasser) zu verbrauchen.')),
                ('e_22', otree.db.models.TableField(choices=[[0, ''], [1, ''], [2, ''], [3, ''], [4, ''], [5, ''], [6, ''], [7, ''], [8, ''], [9, '']], null=True, verbose_name='Die meisten Menschen, die mir wichtig sind, werden es gutheißen, wenn ich versuche, möglichst wenig Ressourcen zu verbrauchen.')),
                ('e_23', otree.db.models.TableField(choices=[[0, ''], [1, ''], [2, ''], [3, ''], [4, ''], [5, ''], [6, ''], [7, ''], [8, ''], [9, '']], null=True, verbose_name='Die meisten Menschen, die mir wichtig sind, versuchen, möglichst wenig Ressourcen zu verbrauchen.')),
                ('e_31', otree.db.models.TableField(choices=[[0, ''], [1, ''], [2, ''], [3, ''], [4, ''], [5, ''], [6, ''], [7, ''], [8, ''], [9, '']], null=True, verbose_name='Ich würde mehr tun, um Ressourcen (z.B. Energie, Wasser) zu sparen, wenn ich wüsste, wie.')),
                ('e_32', otree.db.models.TableField(choices=[[0, ''], [1, ''], [2, ''], [3, ''], [4, ''], [5, ''], [6, ''], [7, ''], [8, ''], [9, '']], null=True, verbose_name='Ob ich mehr oder weniger Ressourcen verbrauche, ändert nicht wirklich etwas an dem Klimaproblem, mit dem wir konfrontiert sind.')),
                ('e_33', otree.db.models.TableField(choices=[[0, ''], [1, ''], [2, ''], [3, ''], [4, ''], [5, ''], [6, ''], [7, ''], [8, ''], [9, '']], null=True, verbose_name='Ich glaube, dass ich zur Lösung des Klimaproblems beitragen kann, indem ich sparsam mit Ressourcen umgehe.')),
                ('e_41', otree.db.models.TableField(choices=[[0, ''], [1, ''], [2, ''], [3, ''], [4, ''], [5, ''], [6, ''], [7, ''], [8, ''], [9, '']], null=True, verbose_name='Ich finde es entspannend zu duschen.')),
                ('e_42', otree.db.models.TableField(choices=[[0, ''], [1, ''], [2, ''], [3, ''], [4, ''], [5, ''], [6, ''], [7, ''], [8, ''], [9, '']], null=True, verbose_name='Ich dusche gerne.')),
                ('e_43', otree.db.models.TableField(choices=[[0, ''], [1, ''], [2, ''], [3, ''], [4, ''], [5, ''], [6, ''], [7, ''], [8, ''], [9, '']], null=True, verbose_name='Duschen ist für mich nur ein Mittel zum Zweck.')),
                ('e_44', otree.db.models.TableField(choices=[[0, ''], [1, ''], [2, ''], [3, ''], [4, ''], [5, ''], [6, ''], [7, ''], [8, ''], [9, '']], null=True, verbose_name='Ich lasse beim Duschen gerne meine Gedanken schweifen.')),
                ('e_45', otree.db.models.TableField(choices=[[0, ''], [1, ''], [2, ''], [3, ''], [4, ''], [5, ''], [6, ''], [7, ''], [8, ''], [9, '']], null=True, verbose_name='Ich versuche, so schnell wie möglich zu duschen.')),
                ('e_53', otree.db.models.BooleanField(choices=[[0, 'Ja, dies war mir bekannt.'], [1, 'Nein, dies war mir bisher nicht bekannt.']], null=True, verbose_name='War Ihnen dies bekannt?')),
                ('e_54', otree.db.models.BooleanField(choices=[[0, 'Ja'], [1, 'Nein']], null=True, verbose_name='Haben Sie schon mindestens einmal einen solchen freiwilligen Ausgleich (beispielsweise für die durch einen Flug entstehenden CO2-Emissionen) gezahlt?')),
                ('e_61', otree.db.models.TableField(choices=[[0, ''], [1, ''], [2, ''], [3, ''], [4, ''], [5, ''], [6, ''], [7, ''], [8, ''], [9, '']], null=True, verbose_name='Freiwillige Ausgleichszahlungen für den Ausstoß von CO2 sind wirksame Klimaschutzmaßnahmen.')),
                ('e_62', otree.db.models.TableField(choices=[[0, ''], [1, ''], [2, ''], [3, ''], [4, ''], [5, ''], [6, ''], [7, ''], [8, ''], [9, '']], null=True, verbose_name='Wenn ich für eine CO2-intensive Tätigkeit (z.B. eine Flugreise) freiwillige Ausgleichszahlungen tätige, dann ist es aus Sicht des Klimaschutzes in Ordnung, auch einen zusätzlichen Flug zu buchen.')),
                ('e_63', otree.db.models.TableField(choices=[[0, ''], [1, ''], [2, ''], [3, ''], [4, ''], [5, ''], [6, ''], [7, ''], [8, ''], [9, '']], null=True, verbose_name='Freiwillige Ausgleichszahlungen können persönliche Klimaschutzanstrengungen nicht ersetzen.')),
                ('comm_1', otree.db.models.StringField(blank=True, max_length=10000, null=True, verbose_name='Platz für Kommentare, falls die Fragen auf dieser Seite unklar sein sollten:')),
                ('comm_2', otree.db.models.StringField(blank=True, max_length=10000, null=True, verbose_name='Platz für Kommentare, falls die Fragen auf dieser Seite unklar sein sollten:')),
                ('comm_3', otree.db.models.StringField(blank=True, max_length=10000, null=True, verbose_name='Platz für Kommentare, falls die Fragen auf dieser Seite unklar sein sollten:')),
                ('comm_4', otree.db.models.StringField(blank=True, max_length=10000, null=True, verbose_name='Platz für Kommentare, falls die Fragen auf dieser Seite unklar sein sollten:')),
                ('comm_5', otree.db.models.StringField(blank=True, max_length=10000, null=True, verbose_name='Platz für Kommentare, falls die Fragen auf dieser Seite unklar sein sollten:')),
                ('comm_6', otree.db.models.StringField(blank=True, max_length=10000, null=True, verbose_name='Platz für Kommentare, falls die Fragen auf dieser Seite unklar sein sollten:')),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='umwelt_einstellung.Group')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='umwelt_einstellung_player', to='otree.Participant')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='umwelt_einstellung_player', to='otree.Session')),
                ('subsession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='umwelt_einstellung.Subsession')),
            ],
            options={
                'db_table': 'umwelt_einstellung_player',
            },
            bases=(models.Model, otree.db.idmap.PlayerIDMapMixin),
        ),
        migrations.AddField(
            model_name='group',
            name='subsession',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='umwelt_einstellung.Subsession'),
        ),
    ]
