# Generated by Django 2.2.12 on 2022-03-23 09:02

from django.db import migrations, models
import django.db.models.deletion
import otree.db.idmap
import otree.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('otree', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_in_subsession', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='umwelt_wissen_group', to='otree.Session')),
            ],
            options={
                'db_table': 'umwelt_wissen_group',
            },
            bases=(models.Model, otree.db.idmap.GroupIDMapMixin),
        ),
        migrations.CreateModel(
            name='Subsession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='umwelt_wissen_subsession', to='otree.Session')),
            ],
            options={
                'db_table': 'umwelt_wissen_subsession',
            },
            bases=(models.Model, otree.db.idmap.SubsessionIDMapMixin),
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_in_group', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('_payoff', otree.db.models.CurrencyField(default=0, null=True)),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('_role', otree.db.models.StringField(max_length=10000, null=True)),
                ('motivation_Wasser', otree.db.models.TableField(choices=[[0, ''], [1, ''], [2, ''], [3, ''], [4, ''], [5, ''], [6, ''], [7, ''], [8, ''], [9, '']], null=True, verbose_name='Ich möchte meinen Ressourcenverbrauch beim Duschen gering halten, weil ich Wasser sparen möchte.')),
                ('motivation_Energie', otree.db.models.TableField(choices=[[0, ''], [1, ''], [2, ''], [3, ''], [4, ''], [5, ''], [6, ''], [7, ''], [8, ''], [9, '']], null=True, verbose_name='Ich möchte meinen Ressourcenverbrauch beim Duschen gering halten, weil ich Energie sparen möchte.')),
                ('motivation_Geld', otree.db.models.TableField(choices=[[0, ''], [1, ''], [2, ''], [3, ''], [4, ''], [5, ''], [6, ''], [7, ''], [8, ''], [9, '']], null=True, verbose_name='Ich möchte meinen Ressourcenverbrauch beim Duschen gering halten, weil ich Geld sparen möchte.')),
                ('Duschmenge', otree.db.models.TableField(null=True, verbose_name='Was denken Sie: Wie viel Wasser wird in Ihrem Haushalt bei einer Dusche verbraucht?')),
                ('Duschmenge_sicher', otree.db.models.TableField(choices=[[0, ''], [1, ''], [2, ''], [3, ''], [4, ''], [5, ''], [6, ''], [7, ''], [8, ''], [9, '']], null=True, verbose_name='Wie sicher sind Sie sich dieser Antwort?')),
                ('Duschdauer', otree.db.models.TableField(null=True, verbose_name='Was denken Sie: Wie lange dauert eine durchschnittliche Dusche in Ihrem Haushalt?')),
                ('Duschdauer_sicher', otree.db.models.TableField(choices=[[0, ''], [1, ''], [2, ''], [3, ''], [4, ''], [5, ''], [6, ''], [7, ''], [8, ''], [9, '']], null=True, verbose_name='Wie sicher sind Sie sich dieser Antwort?')),
                ('Vergleich_Fernseher', otree.db.models.StringField(max_length=10000, null=True, verbose_name='Was denken Sie: Wie viel Energie wird in Ihrem Haushalt benötigt, um das Wasser für eine Dusche zu erwärmen? ')),
                ('Vergleich_Fernseher_sicher', otree.db.models.TableField(choices=[[0, ''], [1, ''], [2, ''], [3, ''], [4, ''], [5, ''], [6, ''], [7, ''], [8, ''], [9, '']], null=True, verbose_name='Wie sicher sind Sie sich dieser Antwort?')),
                ('comm_1', otree.db.models.StringField(blank=True, max_length=10000, null=True, verbose_name='Platz für Kommentare, falls die Fragen auf dieser Seite unklar sein sollten:')),
                ('comm_2', otree.db.models.StringField(max_length=10000, null=True, verbose_name='Platz für Kommentare, falls die Fragen auf dieser Seite unklar sein sollten:')),
                ('comm_3', otree.db.models.StringField(blank=True, max_length=10000, null=True, verbose_name='Platz für Kommentare, falls die Fragen auf dieser Seite unklar sein sollten:')),
                ('comm_1_RTF', otree.db.models.StringField(blank=True, max_length=10000, null=True, verbose_name='Platz für Kommentare, falls die Beschreibungen auf dieser Seite unklar sein sollten:')),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='umwelt_wissen.Group')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='umwelt_wissen_player', to='otree.Participant')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='umwelt_wissen_player', to='otree.Session')),
                ('subsession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='umwelt_wissen.Subsession')),
            ],
            options={
                'db_table': 'umwelt_wissen_player',
            },
            bases=(models.Model, otree.db.idmap.PlayerIDMapMixin),
        ),
        migrations.AddField(
            model_name='group',
            name='subsession',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='umwelt_wissen.Subsession'),
        ),
    ]
