# Generated by Django 2.2.12 on 2022-03-23 09:02

from django.db import migrations, models
import django.db.models.deletion
import otree.db.idmap
import otree.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('otree', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_in_subsession', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intro_group', to='otree.Session')),
            ],
            options={
                'db_table': 'intro_group',
            },
            bases=(models.Model, otree.db.idmap.GroupIDMapMixin),
        ),
        migrations.CreateModel(
            name='Subsession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='intro_subsession', to='otree.Session')),
            ],
            options={
                'db_table': 'intro_subsession',
            },
            bases=(models.Model, otree.db.idmap.SubsessionIDMapMixin),
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_in_group', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('_payoff', otree.db.models.CurrencyField(default=0, null=True)),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('_role', otree.db.models.StringField(max_length=10000, null=True)),
                ('comm_1_RTF', otree.db.models.StringField(blank=True, max_length=10000, null=True, verbose_name='Platz für Kommentare, falls Ihnen die Beschreibungen auf dieser Seite unklar erscheinen')),
                ('vorname', otree.db.models.StringField(max_length=10000, null=True, verbose_name='Vorname')),
                ('nachname', otree.db.models.StringField(max_length=10000, null=True, verbose_name='Nachname')),
                ('straße', otree.db.models.StringField(max_length=10000, null=True, verbose_name='Straße und Hausnummer')),
                ('plz', otree.db.models.TableField(null=True, verbose_name='Postleitzahl')),
                ('stadt', otree.db.models.StringField(max_length=10000, null=True, verbose_name='Stadt')),
                ('email', otree.db.models.StringField(max_length=10000, null=True, verbose_name='E-Mail')),
                ('iban', otree.db.models.StringField(max_length=10000, null=True, verbose_name='IBAN')),
                ('bic', otree.db.models.StringField(max_length=10000, null=True, verbose_name='BIC')),
                ('alter', otree.db.models.TableField(null=True, verbose_name='Alter')),
                ('job', otree.db.models.TableField(choices=[[0, 'Student/Studentin'], [1, 'Berufstätig'], [2, 'Keines zutreffend']], null=True, verbose_name='Was beschreibt Ihre berufliche Situation am Besten?')),
                ('erwachsene', otree.db.models.TableField(null=True, verbose_name='Anzahl der Erwachsenen in Ihrem Haushalt')),
                ('kinder', otree.db.models.TableField(null=True, verbose_name='Anzahl der Kinder in Ihrem Haushalt')),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='intro.Group')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intro_player', to='otree.Participant')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intro_player', to='otree.Session')),
                ('subsession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intro.Subsession')),
            ],
            options={
                'db_table': 'intro_player',
            },
            bases=(models.Model, otree.db.idmap.PlayerIDMapMixin),
        ),
        migrations.AddField(
            model_name='group',
            name='subsession',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intro.Subsession'),
        ),
    ]
