# Generated by Django 2.2.12 on 2022-03-23 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MPL_main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='comm_1_HER',
        ),
        migrations.RemoveField(
            model_name='player',
            name='comm_2_HER',
        ),
        migrations.RemoveField(
            model_name='player',
            name='comm_2_RTF',
        ),
        migrations.RemoveField(
            model_name='player',
            name='comm_3_HER',
        ),
        migrations.RemoveField(
            model_name='player',
            name='comm_3_RTF',
        ),
        migrations.RemoveField(
            model_name='player',
            name='comm_4_RTF',
        ),
    ]
