# Generated by Django 2.2.12 on 2022-03-23 10:59

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('MPL_main', '0002_auto_20220323_1057'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='comm_1_HER',
            field=otree.db.models.StringField(blank=True, max_length=10000, null=True, verbose_name='Platz für Kommentare, falls Ihnen die Beschreibungen auf dieser Seite unklar erscheinen'),
        ),
        migrations.AddField(
            model_name='player',
            name='comm_2_HER',
            field=otree.db.models.StringField(blank=True, max_length=10000, null=True, verbose_name='Platz für Kommentare, falls Ihnen die Beschreibungen auf dieser Seite unklar erscheinen'),
        ),
        migrations.AddField(
            model_name='player',
            name='comm_3_HER',
            field=otree.db.models.StringField(blank=True, max_length=10000, null=True, verbose_name='Platz für Kommentare, falls Ihnen die Fragen auf dieser Seite unklar erscheinen'),
        ),
    ]
