# Generated by Django 2.2.12 on 2022-03-23 09:02

from django.db import migrations, models
import django.db.models.deletion
import otree.db.idmap
import otree.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('otree', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_in_subsession', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duschform_group', to='otree.Session')),
            ],
            options={
                'db_table': 'duschform_group',
            },
            bases=(models.Model, otree.db.idmap.GroupIDMapMixin),
        ),
        migrations.CreateModel(
            name='Subsession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='duschform_subsession', to='otree.Session')),
            ],
            options={
                'db_table': 'duschform_subsession',
            },
            bases=(models.Model, otree.db.idmap.SubsessionIDMapMixin),
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_in_group', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('_payoff', otree.db.models.CurrencyField(default=0, null=True)),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('_role', otree.db.models.StringField(max_length=10000, null=True)),
                ('badewannen_dusche', otree.db.models.IntegerField(choices=[[0, '0'], [1, '1'], [2, '2'], [3, '3'], [4, 'Mehr als 3'], [5, 'Ich weiß es nicht./ Keine Angabe']], null=True, verbose_name='Anzahl an Badewannen mit Dusche (Kombination, wie in Bild 1):')),
                ('seperate_dusche', otree.db.models.IntegerField(choices=[[0, '0'], [1, '1'], [2, '2'], [3, '3'], [4, 'Mehr als 3'], [5, 'Ich weiß es nicht.']], null=True, verbose_name='Anzahl separater Duschen (nicht in einer Badewanne, wie links in Bild 2):')),
                ('seperate_wanne', otree.db.models.IntegerField(choices=[[0, '0'], [1, '1'], [2, '2'], [3, '3'], [4, 'Mehr als 3'], [5, 'Ich weiß es nicht./ Keine Angabe']], null=True, verbose_name='Anzahl separater Badewannen (ohne Dusche / bzw. nicht als Dusche genutzt, wie rechts in Bild 2):')),
                ('kommentare_1', otree.db.models.StringField(blank=True, max_length=10000, null=True, verbose_name='')),
                ('duschkopf_1', otree.db.models.IntegerField(choices=[[0, ''], [1, ''], [2, ''], [3, '']], null=True)),
                ('duschkopf_1_anzahl', otree.db.models.IntegerField(null=True, verbose_name='Wie viele Haushaltsmitglieder nutzen diese Dusche mindestens einmal in der Woche?')),
                ('kommentare_2', otree.db.models.StringField(blank=True, max_length=10000, null=True, verbose_name='Platz für Kommentare')),
                ('besondere_form_1', otree.db.models.IntegerField(choices=[[0, 'Gewöhnliche Form'], [1, 'Außergewöhnliche Form'], [2, 'Ich weiß nicht./ Keine Angabe']], null=True, verbose_name='Der Duschkopf meiner meistgenutzten Dusche hat eine außergewöhnliche Form.')),
                ('besondere_form_1_kom', otree.db.models.StringField(blank=True, max_length=10000, null=True, verbose_name='Falls außergewöhnlich: Mein Duschkopf ist besonders, weil:')),
                ('comm_1', otree.db.models.StringField(blank=True, max_length=10000, null=True, verbose_name='Platz für Kommentare, falls die auf dieser Seite gestellten Fragen unverständlich sind')),
                ('comm_2', otree.db.models.StringField(blank=True, max_length=10000, null=True, verbose_name='Platz für Kommentare, falls die auf dieser Seite gestellten Fragen unverständlich sind')),
                ('comm_3', otree.db.models.StringField(blank=True, max_length=10000, null=True, verbose_name='Platz für Kommentare, falls die auf dieser Seite gestellten Fragen unverständlich sind')),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='duschform.Group')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duschform_player', to='otree.Participant')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duschform_player', to='otree.Session')),
                ('subsession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='duschform.Subsession')),
            ],
            options={
                'db_table': 'duschform_player',
            },
            bases=(models.Model, otree.db.idmap.PlayerIDMapMixin),
        ),
        migrations.AddField(
            model_name='group',
            name='subsession',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='duschform.Subsession'),
        ),
    ]
