# Generated by Django 2.2.12 on 2022-03-23 09:02

from django.db import migrations, models
import django.db.models.deletion
import otree.db.idmap
import otree.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('otree', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_in_subsession', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='psychologie_group', to='otree.Session')),
            ],
            options={
                'db_table': 'psychologie_group',
            },
            bases=(models.Model, otree.db.idmap.GroupIDMapMixin),
        ),
        migrations.CreateModel(
            name='Subsession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='psychologie_subsession', to='otree.Session')),
            ],
            options={
                'db_table': 'psychologie_subsession',
            },
            bases=(models.Model, otree.db.idmap.SubsessionIDMapMixin),
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_in_group', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('_payoff', otree.db.models.CurrencyField(default=0, null=True)),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('_role', otree.db.models.StringField(max_length=10000, null=True)),
                ('P1', otree.db.models.TableField(choices=[[0, 'Nie'], [1, 'Selten'], [2, 'Manchmal'], [3, 'Häufig'], [4, 'Immer']], null=True, verbose_name='Bewerten Sie Ihre Leistung oft anhand selbst gesteckter Ziele?')),
                ('P2', otree.db.models.TableField(choices=[[0, 'Nie'], [1, 'Selten'], [2, 'Manchmal'], [3, 'Häufig'], [4, 'Immer']], null=True, verbose_name='Bewerten Sie Ihre Leistung oft im Vergleich zu den Leistungen Ihrer Freunde/Kollegen?')),
                ('P31', otree.db.models.TableField(choices=[[0, ''], [1, ''], [2, ''], [3, ''], [4, ''], [5, ''], [6, ''], [7, ''], [8, ''], [9, '']], null=True, verbose_name='Es ist mir wichtig, in meine soziale Gruppe (Freundeskreis, Arbeitskollegen, Familie) zu passen.')),
                ('P32', otree.db.models.TableField(choices=[[0, ''], [1, ''], [2, ''], [3, ''], [4, ''], [5, ''], [6, ''], [7, ''], [8, ''], [9, '']], null=True, verbose_name='Mein Verhalten hängt oft von meiner Einschätzung darüber ab, was andere von mir erwarten.')),
                ('P33', otree.db.models.TableField(choices=[[0, ''], [1, ''], [2, ''], [3, ''], [4, ''], [5, ''], [6, ''], [7, ''], [8, ''], [9, '']], null=True, verbose_name='Ich würde meine Meinung (oder die Art und Weise, wie ich Dinge tue) NICHT ändern, um jemand anderem zu gefallen oder seine Gunst zu gewinnen.')),
                ('F1', otree.db.models.TableField(choices=[[0, ''], [1, ''], [2, ''], [3, ''], [4, ''], [5, ''], [6, ''], [7, ''], [8, ''], [9, '']], null=True, verbose_name='Ich mache mir Sorgen darüber, was andere Leute von mir denken werden, auch wenn ich weiß, dass es keine Konsequenzen für mich hat.')),
                ('F2', otree.db.models.TableField(choices=[[0, ''], [1, ''], [2, ''], [3, ''], [4, ''], [5, ''], [6, ''], [7, ''], [8, ''], [9, '']], null=True, verbose_name='Es stört mich, wenn Menschen einen schlechten Eindruck von mir haben.')),
                ('F3', otree.db.models.TableField(choices=[[0, ''], [1, ''], [2, ''], [3, ''], [4, ''], [5, ''], [6, ''], [7, ''], [8, ''], [9, '']], null=True, verbose_name='Ich habe oft Angst davor, dass andere Menschen meine Schwächen bemerken.')),
                ('F4', otree.db.models.TableField(choices=[[0, ''], [1, ''], [2, ''], [3, ''], [4, ''], [5, ''], [6, ''], [7, ''], [8, ''], [9, '']], null=True, verbose_name='Ich mache mir Gedanken darüber, welchen Eindruck ich hinterlasse.')),
                ('F5', otree.db.models.TableField(choices=[[0, ''], [1, ''], [2, ''], [3, ''], [4, ''], [5, ''], [6, ''], [7, ''], [8, ''], [9, '']], null=True, verbose_name='Ich habe Angst, dass andere mich nicht gut finden.')),
                ('F6', otree.db.models.TableField(choices=[[0, ''], [1, ''], [2, ''], [3, ''], [4, ''], [5, ''], [6, ''], [7, ''], [8, ''], [9, '']], null=True, verbose_name='Ich mache mir Gedanken darüber, was andere Menschen von mir halten.')),
                ('F7', otree.db.models.TableField(choices=[[0, ''], [1, ''], [2, ''], [3, ''], [4, ''], [5, ''], [6, ''], [7, ''], [8, ''], [9, '']], null=True, verbose_name='Wenn ich mit jemandem spreche, mache ich mir Sorgen darüber, was er vielleicht über mich denkt.')),
                ('F8', otree.db.models.TableField(choices=[[0, ''], [1, ''], [2, ''], [3, ''], [4, ''], [5, ''], [6, ''], [7, ''], [8, ''], [9, '']], null=True, verbose_name='Normalerweise mache ich mir Gedanken darüber, welchen Eindruck ich hinterlasse.')),
                ('F9', otree.db.models.TableField(choices=[[0, ''], [1, ''], [2, ''], [3, ''], [4, ''], [5, ''], [6, ''], [7, ''], [8, ''], [9, '']], null=True, verbose_name='Wenn ich weiß, dass jemand über mich urteilt, stört mich das.')),
                ('F10', otree.db.models.TableField(choices=[[0, ''], [1, ''], [2, ''], [3, ''], [4, ''], [5, ''], [6, ''], [7, ''], [8, ''], [9, '']], null=True, verbose_name='Manchmal denke ich, ich mache mir zu viele Gedanken darüber, was andere Menschen von mir denken.')),
                ('F11', otree.db.models.TableField(choices=[[0, ''], [1, ''], [2, ''], [3, ''], [4, ''], [5, ''], [6, ''], [7, ''], [8, ''], [9, '']], null=True, verbose_name='Ich mache mir oft Sorgen, dass ich falsche Dinge sage oder tue.')),
                ('comm_1', otree.db.models.StringField(blank=True, max_length=10000, null=True, verbose_name='Platz für Kommentare, falls die Fragen auf dieser Seite unklar sein sollten:')),
                ('comm_2', otree.db.models.StringField(max_length=10000, null=True, verbose_name='Platz für Kommentare, falls die Fragen auf dieser Seite unklar sein sollten:')),
                ('comm_3', otree.db.models.StringField(blank=True, max_length=10000, null=True, verbose_name='Platz für Kommentare, falls die Fragen auf dieser Seite unklar sein sollten:')),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='psychologie.Group')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='psychologie_player', to='otree.Participant')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='psychologie_player', to='otree.Session')),
                ('subsession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='psychologie.Subsession')),
            ],
            options={
                'db_table': 'psychologie_player',
            },
            bases=(models.Model, otree.db.idmap.PlayerIDMapMixin),
        ),
        migrations.AddField(
            model_name='group',
            name='subsession',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='psychologie.Subsession'),
        ),
    ]
