# Generated by Django 2.2.12 on 2022-03-23 09:02

from django.db import migrations, models
import django.db.models.deletion
import otree.db.idmap
import otree.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('otree', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_in_subsession', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='essen_group', to='otree.Session')),
            ],
            options={
                'db_table': 'essen_group',
            },
            bases=(models.Model, otree.db.idmap.GroupIDMapMixin),
        ),
        migrations.CreateModel(
            name='Subsession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='essen_subsession', to='otree.Session')),
            ],
            options={
                'db_table': 'essen_subsession',
            },
            bases=(models.Model, otree.db.idmap.SubsessionIDMapMixin),
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_in_group', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('_payoff', otree.db.models.CurrencyField(default=0, null=True)),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('_role', otree.db.models.StringField(max_length=10000, null=True)),
                ('KWE1a', otree.db.models.TableField(choices=[[0, ''], [1, ''], [2, ''], [3, ''], [4, ''], [5, ''], [6, ''], [7, ''], [8, ''], [9, '']], null=True, verbose_name='... zur ersten Gruppe gehört?')),
                ('KWE2a', otree.db.models.TableField(choices=[[0, ''], [1, ''], [2, ''], [3, ''], [4, ''], [5, ''], [6, ''], [7, ''], [8, ''], [9, '']], null=True, verbose_name='... zur zweiten Gruppe gehört?')),
                ('KWE3a', otree.db.models.TableField(choices=[[0, ''], [1, ''], [2, ''], [3, ''], [4, ''], [5, ''], [6, ''], [7, ''], [8, ''], [9, '']], null=True, verbose_name='... zur dritten Gruppe gehört?')),
                ('KWE4a', otree.db.models.TableField(choices=[[0, ''], [1, ''], [2, ''], [3, ''], [4, ''], [5, ''], [6, ''], [7, ''], [8, ''], [9, '']], null=True, verbose_name='... zur vierten Gruppe gehört?')),
                ('KWE1', otree.db.models.TableField(choices=[[0, ''], [1, ''], [2, ''], [3, ''], [4, ''], [5, ''], [6, ''], [7, ''], [8, ''], [9, '']], null=True, verbose_name='... zur ersten Gruppe gehört?')),
                ('KWE2', otree.db.models.TableField(choices=[[0, ''], [1, ''], [2, ''], [3, ''], [4, ''], [5, ''], [6, ''], [7, ''], [8, ''], [9, '']], null=True, verbose_name='... zur zweiten Gruppe gehört?')),
                ('KWE3', otree.db.models.TableField(choices=[[0, ''], [1, ''], [2, ''], [3, ''], [4, ''], [5, ''], [6, ''], [7, ''], [8, ''], [9, '']], null=True, verbose_name='... zur dritten Gruppe gehört?')),
                ('KWE4', otree.db.models.TableField(choices=[[0, ''], [1, ''], [2, ''], [3, ''], [4, ''], [5, ''], [6, ''], [7, ''], [8, ''], [9, '']], null=True, verbose_name='... zur vierten Gruppe gehört?')),
                ('e_10', otree.db.models.TableField(choices=[[0, ''], [1, ''], [2, ''], [3, ''], [4, ''], [5, ''], [6, ''], [7, ''], [8, ''], [9, '']], null=True, verbose_name='Ich bin bereit, mich klimafreundlich zu verhalten, auch wenn dies mit höheren Kosten und Anstrengungen verbunden ist.')),
                ('e_11', otree.db.models.TableField(choices=[[0, ''], [1, ''], [2, ''], [3, ''], [4, ''], [5, ''], [6, ''], [7, ''], [8, ''], [9, '']], null=True, verbose_name='Ich bin bereit, meine Treibhausgasemissionen gering zu halten, auch wenn dies mit höheren Kosten und Anstrengungen verbunden ist.')),
                ('e_12', otree.db.models.TableField(choices=[[0, ''], [1, ''], [2, ''], [3, ''], [4, ''], [5, ''], [6, ''], [7, ''], [8, ''], [9, '']], null=True, verbose_name='Ich bin nur dann bereit, meine Treibhausgasemissionen gering zu halten, wenn andere das auch tun.')),
                ('e_13', otree.db.models.TableField(choices=[[0, ''], [1, ''], [2, ''], [3, ''], [4, ''], [5, ''], [6, ''], [7, ''], [8, ''], [9, '']], null=True, verbose_name='Es entspricht meinen Prinzipien, meine Treibhausgasemissionen möglichst gering zu halten.')),
                ('e_14', otree.db.models.TableField(choices=[[0, ''], [1, ''], [2, ''], [3, ''], [4, ''], [5, ''], [6, ''], [7, ''], [8, ''], [9, '']], null=True, verbose_name='Ich fühle mich persönlich dafür verantwortlich, meine Treibhausgasemissionen möglichst niedrig zu halten.')),
                ('fav_essen', otree.db.models.StringField(choices=[('Cremige Gemüselasagne', 'Cremige Gemüselasagne'), ('Tagliatelle mit Lachs-Sahne-Sauce', 'Tagliatelle mit Lachs-Sahne-Sauce'), ('Blumenkohl-Bohnen-Curry mit Tofu und Reis', 'Blumenkohl-Bohnen-Curry mit Tofu und Reis'), ('Cheeseburger mit Pommes frites', 'Cheeseburger mit Pommes frites')], max_length=10000, null=True)),
                ('fav_essen_why', otree.db.models.StringField(max_length=10000, null=True, verbose_name='Warum haben Sie sich für dieses Gericht entschieden?')),
                ('platz_1', otree.db.models.StringField(choices=[('Cremige Gemüselasagne', 'Cremige Gemüselasagne'), ('Tagliatelle mit Lachs-Sahne-Sauce', 'Tagliatelle mit Lachs-Sahne-Sauce'), ('Blumenkohl-Bohnen-Curry mit Tofu und Reis', 'Blumenkohl-Bohnen-Curry mit Tofu und Reis'), ('Cheeseburger mit Pommes frites', 'Cheeseburger mit Pommes frites')], max_length=10000, null=True, verbose_name='')),
                ('fav_essen_geschmack', otree.db.models.TableField(choices=[[0, ''], [1, ''], [2, ''], [3, ''], [4, ''], [5, ''], [6, ''], [7, ''], [8, ''], [9, '']], null=True, verbose_name='Geschmack')),
                ('fav_essen_gesund', otree.db.models.TableField(choices=[[0, ''], [1, ''], [2, ''], [3, ''], [4, ''], [5, ''], [6, ''], [7, ''], [8, ''], [9, '']], null=True, verbose_name='Gesund')),
                ('fav_essen_kalorienarm', otree.db.models.TableField(choices=[[0, ''], [1, ''], [2, ''], [3, ''], [4, ''], [5, ''], [6, ''], [7, ''], [8, ''], [9, '']], null=True, verbose_name='Kalorienarm')),
                ('fav_essen_vegetarisch', otree.db.models.TableField(choices=[[0, ''], [1, ''], [2, ''], [3, ''], [4, ''], [5, ''], [6, ''], [7, ''], [8, ''], [9, '']], null=True, verbose_name='Tierschutzaspekte')),
                ('fav_essen_vegetarisch2', otree.db.models.TableField(choices=[[0, ''], [1, ''], [2, ''], [3, ''], [4, ''], [5, ''], [6, ''], [7, ''], [8, ''], [9, '']], null=True, verbose_name='Umweltaspekte')),
                ('fav_essen_neues', otree.db.models.TableField(choices=[[0, ''], [1, ''], [2, ''], [3, ''], [4, ''], [5, ''], [6, ''], [7, ''], [8, ''], [9, '']], null=True, verbose_name='Etwas Neues probieren wollen')),
                ('fav_essen_altes', otree.db.models.TableField(choices=[[0, ''], [1, ''], [2, ''], [3, ''], [4, ''], [5, ''], [6, ''], [7, ''], [8, ''], [9, '']], null=True, verbose_name='Sicher sein zu können, dass mir das Gericht schmecken wird')),
                ('fav_essen_kochen', otree.db.models.TableField(choices=[[0, ''], [1, ''], [2, ''], [3, ''], [4, ''], [5, ''], [6, ''], [7, ''], [8, ''], [9, '']], null=True, verbose_name='Etwas essen, was ich mir nicht selbst kochen würde (zu aufwendig)')),
                ('fav_essen_teuer', otree.db.models.TableField(choices=[[0, ''], [1, ''], [2, ''], [3, ''], [4, ''], [5, ''], [6, ''], [7, ''], [8, ''], [9, '']], null=True, verbose_name='Etwas essen, was im Restaurant möglichst teuer wäre - ich bekäme es hier ja geschenkt.')),
                ('platz_2', otree.db.models.StringField(choices=[('Cremige Gemüselasagne', 'Cremige Gemüselasagne'), ('Tagliatelle mit Lachs-Sahne-Sauce', 'Tagliatelle mit Lachs-Sahne-Sauce'), ('Blumenkohl-Bohnen-Curry mit Tofu und Reis', 'Blumenkohl-Bohnen-Curry mit Tofu und Reis'), ('Cheeseburger mit Pommes frites', 'Cheeseburger mit Pommes frites')], max_length=10000, null=True, verbose_name='')),
                ('platz_3', otree.db.models.StringField(choices=[('Cremige Gemüselasagne', 'Cremige Gemüselasagne'), ('Tagliatelle mit Lachs-Sahne-Sauce', 'Tagliatelle mit Lachs-Sahne-Sauce'), ('Blumenkohl-Bohnen-Curry mit Tofu und Reis', 'Blumenkohl-Bohnen-Curry mit Tofu und Reis'), ('Cheeseburger mit Pommes frites', 'Cheeseburger mit Pommes frites')], max_length=10000, null=True, verbose_name='')),
                ('platz_4', otree.db.models.StringField(choices=[('Cremige Gemüselasagne', 'Cremige Gemüselasagne'), ('Tagliatelle mit Lachs-Sahne-Sauce', 'Tagliatelle mit Lachs-Sahne-Sauce'), ('Blumenkohl-Bohnen-Curry mit Tofu und Reis', 'Blumenkohl-Bohnen-Curry mit Tofu und Reis'), ('Cheeseburger mit Pommes frites', 'Cheeseburger mit Pommes frites')], max_length=10000, null=True, verbose_name='')),
                ('platz_warum', otree.db.models.StringField(max_length=10000, null=True, verbose_name='Woran haben Sie sich bei dieser Schätzung orientiert/ Was haben Sie in Betracht gezogen?')),
                ('magnitude', otree.db.models.TableField(choices=[[0, 'Die Emissionen von Gericht A sind weniger als 1.25- mal so hoch wie die Emissionen von Gericht B.'], [1, 'Die Emissionen von Gericht A sind zwischen 1.25- und 1.5- mal so hoch wie die Emissionen von Gericht B.'], [2, 'Die Emissionen von Gericht A sind zwischen 1.5- und 2- mal so hoch wie die Emissionen von Gericht B.'], [3, 'Die Emissionen von Gericht A sind zwischen 2- und 3- mal so hoch wie die Emissionen von Gericht B.'], [4, 'Die Emissionen von Gericht A sind zwischen 3- und 4- mal so hoch wie die Emissionen von Gericht B.'], [5, 'Die Emissionen von Gericht A sind zwischen 4- und 5- mal so hoch wie die Emissionen von Gericht B.'], [6, 'Die Emissionen von Gericht A sind mehr als 5- mal so hoch wie die Emissionen von Gericht B.']], null=True, verbose_name='')),
                ('drive', otree.db.models.TableField(null=True, verbose_name='')),
                ('comm_1', otree.db.models.StringField(blank=True, max_length=10000, null=True, verbose_name='Hier finden Sie Platz für Kommentare, falls die Fragen auf dieser Seite unklar sein sollten:')),
                ('comm_2', otree.db.models.StringField(blank=True, max_length=10000, null=True, verbose_name='Hier finden Sie Platz für Kommentare, falls diese Frage unklar sein sollte:')),
                ('comm_3', otree.db.models.StringField(blank=True, max_length=10000, null=True, verbose_name='Hier finden Sie Platz für Kommentare, falls diese Frage unklar sein sollte:')),
                ('comm_3b', otree.db.models.StringField(blank=True, max_length=10000, null=True, verbose_name='Hier finden Sie Platz für Kommentare, falls die Fragen auf dieser Seite unklar sein sollten:')),
                ('comm_4', otree.db.models.StringField(blank=True, max_length=10000, null=True, verbose_name='Hier finden Sie Platz für Kommentare, falls die Fragen auf dieser Seite unklar sein sollten:')),
                ('comm_5', otree.db.models.StringField(blank=True, max_length=10000, null=True, verbose_name='Hier finden Sie Platz für Kommentare, falls diese Frage unklar sein sollte:')),
                ('comm_6', otree.db.models.StringField(blank=True, max_length=10000, null=True, verbose_name='Hier finden Sie Platz für Kommentare, falls diese Frage unklar sein sollte:')),
                ('comm_7', otree.db.models.StringField(blank=True, max_length=10000, null=True, verbose_name='Hier finden Sie Platz für Kommentare, falls diese Frage unklar sein sollte:')),
                ('comm_8', otree.db.models.StringField(blank=True, max_length=10000, null=True, verbose_name='Hier finden Sie Platz, falls Sie allgemeine Kommentare zu dieser Umfrage haben')),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='essen.Group')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='essen_player', to='otree.Participant')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='essen_player', to='otree.Session')),
                ('subsession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='essen.Subsession')),
            ],
            options={
                'db_table': 'essen_player',
            },
            bases=(models.Model, otree.db.idmap.PlayerIDMapMixin),
        ),
        migrations.AddField(
            model_name='group',
            name='subsession',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='essen.Subsession'),
        ),
    ]
